import networkx as nx
import matplotlib.pyplot as plt
import time

# Generate a random graph with 100 nodes
G = nx.gnp_random_graph(100, 0.1)


# Define DFS algorithm
def DFS(graph, start_node):
    visited = []
    stack = [start_node]
    while stack:
        node = stack.pop()
        if node not in visited:
            visited.append(node)
            stack.extend([n for n in graph.neighbors(node) if n not in visited])
    return visited


# Define BFS algorithm
def BFS(graph, start_node):
    visited = []
    queue = [start_node]
    while queue:
        node = queue.pop(0)
        if node not in visited:
            visited.append(node)
            queue.extend([n for n in graph.neighbors(node) if n not in visited])
    return visited


# Measure the execution time of DFS and BFS algorithms for graphs of different sizes
dfs_times = []
bfs_times = []
node_counts = []
for n in range(10, 110, 10):
    node_counts.append(n)
    graph = nx.gnp_random_graph(n, 0.1)

    start_time = time.time()
    DFS(graph, 0)
    end_time = time.time()
    dfs_times.append(end_time - start_time)

    start_time = time.time()
    BFS(graph, 0)
    end_time = time.time()
    bfs_times.append(end_time - start_time)

# Plot the execution times of DFS and BFS algorithms as a function of the number of nodes
plt.plot(node_counts, dfs_times, 'r-', label='DFS')
plt.plot(node_counts, bfs_times, 'b-', label='BFS')
plt.xlabel('Number of nodes')
plt.ylabel('Execution time (seconds)')
plt.title('Comparison of DFS and BFS algorithms')
plt.legend()
plt.show()

# Generate a graph with 100 nodes and plot the trees generated by DFS and BFS algorithms
G = nx.gnp_random_graph(100, 0.1)

# Compute DFS tree
dfs_tree = nx.dfs_tree(G, 0)

# Compute BFS tree
bfs_tree = nx.bfs_tree(G, 0)

# Plot the original graph and the DFS and BFS trees
pos = nx.spring_layout(G)
plt.subplot(1, 3, 1)
nx.draw(G, pos, with_labels=True)
plt.title('Original graph')
plt.subplot(1, 3, 2)
nx.draw(dfs_tree, pos, with_labels=True)
plt.title('DFS tree')
plt.subplot(1, 3, 3)
nx.draw(bfs_tree, pos, with_labels=True)
plt.title('BFS tree')
plt.show()